// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_through_and_through = "CgkIy8DmhfsXEAIQCQ"; // <GPGSID>
        public const string achievement_efficient = "CgkIy8DmhfsXEAIQCA"; // <GPGSID>
        public const string achievement_bubble_bath = "CgkIy8DmhfsXEAIQAw"; // <GPGSID>
        public const string achievement_the_trickster = "CgkIy8DmhfsXEAIQAg"; // <GPGSID>
        public const string achievement_cheers_you_lost = "CgkIy8DmhfsXEAIQAQ"; // <GPGSID>
        public const string achievement_welcome_home = "CgkIy8DmhfsXEAIQAA"; // <GPGSID>
        public const string achievement_sleep_well = "CgkIy8DmhfsXEAIQBA"; // <GPGSID>
        public const string achievement_relax = "CgkIy8DmhfsXEAIQBg"; // <GPGSID>
        public const string achievement_dinners_ready = "CgkIy8DmhfsXEAIQBQ"; // <GPGSID>
        public const string achievement_underground_escape = "CgkIy8DmhfsXEAIQBw"; // <GPGSID>

}

